# Generated by Django 3.1.3 on 2020-12-15 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Twit',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('search_key_word', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('twits', models.CharField(max_length=10000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'result',
            },
        ),
    ]
