# Generated by Django 3.1.3 on 2020-12-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20201215_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twit',
            name='user',
        ),
    ]
