# Generated by Django 3.1.3 on 2020-12-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_remove_twit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='twits',
            field=models.CharField(max_length=100000),
        ),
    ]
