# Generated by Django 3.1.3 on 2020-12-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20201215_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='twits',
            field=models.CharField(max_length=1000000),
        ),
    ]
