# Generated by Django 3.1.3 on 2020-12-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20201215_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='clean_twits',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
