# Generated by Django 3.1.3 on 2021-01-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_twit_clean_twits'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='user',
            field=models.EmailField(default=-1.0, max_length=255, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
