# Generated by Django 3.1.3 on 2021-01-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_twit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='clean_twits',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='twit',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
