# Generated by Django 3.1.3 on 2021-01-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_auto_20210112_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='fatma',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
