# Generated by Django 3.1.3 on 2021-01-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0010_auto_20210112_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='cooked',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AddField(
            model_name='twit',
            name='word_count',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
